# Generated by Django 2.0.5 on 2018-12-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FourDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=20)),
                ('plant_start', models.IntegerField(null=True)),
                ('plant_end', models.IntegerField(null=True)),
                ('harvest_start', models.IntegerField(null=True)),
                ('harvest_end', models.IntegerField(null=True)),
                ('flag', models.BooleanField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four_dates.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agro_eco_zone', models.CharField(max_length=200)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='four_dates.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subregion',
            name='sub_region_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='four_dates.SubRegionUnit'),
        ),
        migrations.AddField(
            model_name='fourdates',
            name='sub_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four_dates.SubRegion'),
        ),
    ]
