# Generated by Django 2.0.5 on 2019-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregion',
            name='agro_eco_zone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
