# Generated by Django 2.0.5 on 2019-01-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_dates', '0002_auto_20190103_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourdates',
            name='source_file',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
