# Generated by Django 2.0.5 on 2019-01-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_dates', '0004_auto_20190103_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourdates',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
